branch-defaults:
  master:
    environment: SWAPDROP-test
    group_suffix: null
  staging:
    environment: SWAPDROP-staging
global:
  application_name: SWAPDROP
  branch: null
  default_ec2_keyname: swapdrop-ssh
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
