version: 2
jobs:
    eb_deploy:
        steps:
            - run:
                  command: |
                      pip install awsebcli
                      eb use SWAPDROP-staging --profile default
                      eb deploy --profile default
workflows:
    version: 2
    staging_deploy:
        jobs:
            - eb_deploy:
                filters:
                    branches:
                      only:
                       - staging



