version: 2
jobs: 
    deploy:
        steps:
            -run:
                name: elastic beanstalk deployment
                command: |
                    pip install awsebcli
                    eb use SWAPDROP-staging --profile default
                    eb deploy --profile default

workflows:
    version: 2
    staging_deploy:
        jobs:
            - deploy
                filters:
                    branches:
                        only:
                            - staging
