version: 2
jobs:
    eb_deploy:
      docker:
        - image: circleci/python:3.6.8
      steps:
        - checkout
        - run:
           command: |
              pip install --upgrade pip
              sudo pip install awsebcli==3.18.1
              eb use SWAPDROP-staging
              eb deploy
workflows:
    version: 2
    staging_deploy:
        jobs:
            - eb_deploy:
                filters:
                    branches:
                      only:
                       - staging



