# Generated by Django 3.0.5 on 2020-06-02 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import products.model_enums
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pics', validators=[products.validators.is_square_image])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=products.model_enums.ProductStatus)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
