# Generated by Django 3.0.5 on 2020-05-06 06:08

from django.db import migrations
import django_enumfield.db.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200429_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=products.models.ProductStatus),
        ),
    ]
