# Generated by Django 3.0.5 on 2020-05-08 11:29

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics', validators=[products.validators.is_square_image]),
        ),
    ]
