# Generated by Django 3.0.5 on 2020-05-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('house_name_number', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=50)),
                ('address_line_2', models.CharField(blank=True, max_length=50)),
                ('town_city', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=13)),
                ('gender_preference', models.ManyToManyField(to='sizes.GenderPreference')),
                ('primary_sizes', models.ManyToManyField(to='sizes.Size')),
                ('shoe_sizes', models.ManyToManyField(to='sizes.ShoeSize')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waist_sizes', models.ManyToManyField(to='sizes.WaistSize')),
            ],
        ),
    ]
