# Generated by Django 3.0.5 on 2020-05-30 16:19

from django.db import migrations, models
import django_enumfield.db.fields
import sizes.model_enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', django_enumfield.db.fields.EnumField(enum=sizes.model_enums.GenderOptions)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', django_enumfield.db.fields.EnumField(enum=sizes.model_enums.GenderOptions)),
                ('size', django_enumfield.db.fields.EnumField(enum=sizes.model_enums.PrimarySizeOptions)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', django_enumfield.db.fields.EnumField(enum=sizes.model_enums.ShoeSizeOptions)),
            ],
        ),
        migrations.CreateModel(
            name='WaistSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', django_enumfield.db.fields.EnumField(enum=sizes.model_enums.WaistSizeOptions)),
            ],
        ),
    ]
