# Generated by Django 3.0.5 on 2020-05-05 07:30

from django.db import migrations
import django_enumfield.db.fields
import matches.models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=matches.models.OfferStatus),
        ),
    ]
