# Generated by Django 3.0.5 on 2020-05-06 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_liked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_offered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
